---

# - import_tasks: avahi.yml

- name: Install cups, ghostscript
  pacman:
    name:
      - cups
      - ghostscript
    state: present
  become: yes

- name: Enable org.cups.cupsd.socket
  systemd:
    name: org.cups.cupsd.socket
    enabled: yes
  become: yes

