---

- name: Install fcitx5, fcitx5-gtk, fcitx5-qt, fcitx5-anthy, fcitx5-chinese-addons, fcitx5-hangul, kcm-fcitx5
  pacman:
    name:
      - fcitx5
      - fcitx5-gtk
      - fcitx5-qt
      - fcitx5-anthy
      - fcitx5-chinese-addons
      - fcitx5-hangul
      - kcm-fcitx5
    state: present
  become: yes

- name: Copy fcitx5 config
  copy:
    src: fcitx5
    dest: "{{ ansible_user_dir }}/.config/"
