---

- name: Install firefox
  pacman:
    name: firefox
    state: present
  become: yes

# fcitx5 not working on wayland mode
# - name: Install firefox
#   flatpak:
#     name: org.mozilla.firefox
#     state: present
#   become: yes
