---

- name: Install i3status-rust
  pacman:
    name: "{{ role_path }}/files/i3status-rust-0.14.1-1-any.pkg.tar.xz"
    state: present
  become: yes

- name: Create $HOME/.config/i3status-rs directory if it does not exist
  file:
    path: "{{ ansible_user_dir }}/.config/i3status-rs"
    state: directory

- name: Copy i3status-rs config
  copy:
    src: i3status-rs-config.toml
    dest: "{{ ansible_user_dir }}/.config/i3status-rs/config.toml"
