---

- name: Install kanshi
  pacman:
    name: kanshi
    state: present
  become: yes

- name: Create $HOME/.config/kanshi directory if it does not exist
  file:
    path: "{{ ansible_user_dir }}/.config/kanshi"
    state: directory

- name: Copy kanshi config
  copy:
    src: kanshi.config
    dest: "{{ ansible_user_dir }}/.config/kanshi/config"
