---

- name: Install blueman, feh, mpv, pulseaudio-bluetooth
  pacman:
    name:
      - blueman
      - feh
      - mpv
      # - pulseaudio-dlna
      - pulseaudio-bluetooth
    state: present
  become: yes

- name: Install pavucontrol
  flatpak:
    name: org.pulseaudio.pavucontrol
    state: present
  become: yes

- name: Copy mpv config
  copy:
    src: mpv
    dest: "{{ ansible_user_dir }}/.config/"

- name: Install youtube_dl
  pip:
    name: youtube_dl
    executable: "{{ ansible_user_dir }}/.local/bin/pip"
    extra_args: --user
    state: latest

# - name: Copy pulseaudio-dlna.service
#   copy:
#     src: systemd/user/pulseaudio-dlna.service
#     dest: "{{ ansible_user_dir }}/.config/systemd/user/"
