---

- name: Install modemmanager, networkmanager
  pacman:
    name:
      - modemmanager
      - networkmanager
    state: present
  become: yes

- name: Enable and start NetworkManager
  systemd:
    name: NetworkManager
    enabled: yes
    state: started
  become: yes
