---

- name: Tap cask-fonts repositories
  homebrew_tap:
    name: homebrew/cask-fonts
    state: present

- name: Install alacritty
  homebrew_cask:
    name: "{{ item }}"
    state: present
  with_items:
    - alacritty
    - font-cica

- name: Create $HOME/.config/alacritty directory if it does not exist
  file:
    path: "{{ ansible_user_dir }}/.config/alacritty"
    state: directory

- name: Copy alacritty config
  template:
    src: "{{ role_path | dirname }}/gui/templates/alacritty.yml.j2"
    dest: "{{ ansible_user_dir }}/.config/alacritty/alacritty.yml"
