---

- name: Install packages of pinentry-mac, gopass, choose-gui
  homebrew:
    name:
      - pinentry-mac
      - gopass
      - choose-gui
    state: present

- name: Install cask packages of icanhazshortcut
  homebrew_cask:
    name: "{{ item }}"
    state: present
  with_items:
    - icanhazshortcut

- name: Create $HOME/.gnupg directory if it does not exist
  file:
    path: "{{ ansible_user_dir }}/.gnupg"
    state: directory

- name: Copy gpg-agent.conf
  copy:
    src: gpg-agent.conf
    dest: "{{ ansible_user_dir }}/.gnupg/"
