---

- name: Install ansible
  homebrew:
    name: ansible
    state: present

- name: Install cask packages of alfred, dbeaver-community, firefox, google-japanese-ime, insomnia, joplin, karabiner-elements, rectangle, slack
  homebrew_cask:
    name: "{{ item }}"
    state: present
    accept_external_apps: true
  with_items:
    - alfred
    - dbeaver-community
    - firefox
    # - google-chrome
    - google-japanese-ime
    - insomnia
    - joplin
    - karabiner-elements
    - rectangle
    - slack

- import_tasks: alacritty.yml
  tags: alacritty
- import_tasks: vagrant.yml
  tags: vagrant
