---

- name: Install packages of ansible
  homebrew:
    name:
      - ansible
    state: present

- name: Install cask packages of appcleaner, dbeaver-community, firefox, font-cica, google-japanese-ime, insomnia, joplin, rectangle, slack, zoomus
  homebrew_cask:
    name: "{{ item }}"
    state: present
    accept_external_apps: true
  with_items:
    - appcleaner
    - dbeaver-community
    - firefox
    - google-japanese-ime
    - insomnia
    - joplin
    - rectangle
    - slack
    - zoomus

- import_tasks: gopass.yml
  tags: gopass
- import_tasks: karabiner.yml
  tags: karabiner
- import_tasks: alacritty.yml
  tags: alacritty
- import_tasks: vagrant.yml
  tags: vagrant
