---

- name: Install vagrant, virtualbox
  homebrew_cask:
    name: "{{ item }}"
    state: present
    accept_external_apps: true
  with_items:
    - vagrant
    - virtualbox

- name: Start up vagrant
  debug:
    msg: Execute `vagrant up`
