---

- name: Tap repositories
  homebrew_tap:
    name: koekeishiya/formulae
    state: present

- name: Install yabai, skhd, jq
  homebrew:
    name:
      - yabai
      - skhd
      - jq
    state: present

- name: Install cask packages of font-fontawesome, ubersicht
  homebrew_cask:
    name: "{{ item }}"
    state: present
  with_items:
    - font-fontawesome
    - ubersicht

- name: Copy yabai config
  copy:
    src: yabairc
    dest: "{{ ansible_user_dir }}/.yabairc"

- name: Copy skhd config
  copy:
    src: skhdrc
    dest: "{{ ansible_user_dir }}/.skhdrc"

- name: Copy Übersicht widgets config
  copy:
    src: Übersicht
    dest: "{{ ansible_user_dir }}/Library/Application\ Support/"
    mode: preserve
