---

- name: Install go
  pacman:
    name: go
    state: present
  become: yes

- name: Config fish for go
  copy:
    src: fish/go.fish
    dest: "{{ ansible_user_dir }}/.config/fish/conf.d/"
  tags: fish
