---

- name: Install python
  pacman:
    name: python
    state: present
  become: yes

- name: Check install of pip
  stat:
    path: "{{ ansible_user_dir }}/.local/bin/pip"
  register: pip

- name: Install pip
  shell: |
    curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
    python get-pip.py --user
    rm get-pip.py
  args:
    warn: no
  when: pip.stat.exists == False

- name: Install ansible, black, flake8, pre-commit
  pip:
    name:
      - ansible
      - black
      - flake8
      - pre-commit
      #- python-language-server
    executable: "{{ ansible_user_dir }}/.local/bin/pip"
    extra_args: --user
    state: latest

- name: Config fish for python
  copy:
    src: fish/python.fish
    dest: "{{ ansible_user_dir }}/.config/fish/conf.d/"
  tags: fish
