---

- name: Install git, github-cli
  pacman:
    name:
      - git
      - github-cli
    state: present
  become: yes

- name: Copy git config
  copy:
    src: git/{{ item }}
    dest: "{{ ansible_user_dir }}/.git{{ item }}"
    force: no
  with_items:
    - config
    - config_supplement

- name: Copy gitignore config
  copy:
    src: git/ignore
    dest: "{{ ansible_user_dir }}/.config/git/"
    force: no

- name: Config fish for git
  copy:
    src: fish/git.fish
    dest: "{{ ansible_user_dir }}/.config/fish/conf.d/"
  tags: fish
