---

- name: Install ruby
  pacman:
    name: ruby
    state: present
  become: yes

- name: Install ruby packages of pre-commit
  gem:
    name: pre-commit
    state: latest

- name: Config fish for ruby
  copy:
    src: fish/ruby.fish
    dest: "{{ ansible_user_dir }}/.config/fish/conf.d/"
  tags: fish
