---

- name: Install rust
  pacman:
    name: rust
    state: present
  become: yes

- name: Config fish for rust
  copy:
    src: fish/rust.fish
    dest: "{{ ansible_user_dir }}/.config/fish/conf.d/"
  tags: fish

# - name: Check install of rustup
#   stat:
#     path: "{{ ansible_user_dir }}/.cargo/bin/rustup"
#   register: rustup
#   
# - name: Install rustup
#   shell: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --no-modify-path --component rust-src
#   args:
#     warn: no
#   when: rustup.stat.exists == False
