---

- name: Install rust
  pacman:
    name: rustup
    state: present
  become: yes

- name: Config fish for rust
  copy:
    src: fish/rust.fish
    dest: "{{ ansible_user_dir }}/.config/fish/conf.d/"
  tags: fish
