---

- name: Copy starship package
  copy:
    src: starship-0.41.3-1-x86_64.pkg.tar.xz
    dest: "{{ ansible_user_dir }}/packages/"

- name: Install starship
  pacman:
    name: "{{ ansible_user_dir }}/packages/starship-0.41.3-1-x86_64.pkg.tar.xz"
    state: present
  become: yes

- name: Config fish for starship
  copy:
    src: fish/starship.fish
    dest: "{{ ansible_user_dir }}/.config/fish/conf.d/"
  tags: fish
