---

- name: Check if yay is installed
  stat:
    path: /usr/bin/yay
  register: yay

- name: Install yay
  shell: |
    git clone https://aur.archlinux.org/yay.git
    cd yay
    makepkg --syncdeps --install --noconfirm
    cd ..
    rm -r yay
  when: yay.stat.exists == False

- name: Create $HOME/.config/yay directory if it does not exist
  file:
    path: "{{ ansible_user_dir }}/.config/yay"
    state: directory

- name: Config yay
  copy:
    src: yay-config.json
    dest: "{{ ansible_user_dir }}/.config/yay/config.json"

- name: Config fish for yay
  copy:
    src: fish/yay.fish
    dest: "{{ ansible_user_dir }}/.config/fish/conf.d/"
  tags: fish
